---
title: "Présention du cours"
output:
    html_document:
      toc: true
      toc_float: true
      number_sections: false
      theme: journal
      highlight: textmate
---

```{r eval=FALSE, echo=FALSE}
rmarkdown::render_site()
install.packages("knitr")
install.packages("rmarkdown")
```


Programme du cours **Data visualisation en actuariat**


# Objectifs et projets {.tabset}

## Objectifs

- Visualiser pour mieux comprendre certaines notions de base en actuariat. Donc ce sera l'occasion de revoir certaines notions classiques en actuariat, et grâce à la visualisation, mieux comprendre ces notions (sinistralité, copules, simulations en finance, modèles de taux, etc)
- Apprendre à communiquer les données de façon pertinente et visuelle (visualisation des données géographiques, interactivité des graphiques, production de dashbord, etc)
- Maîtriser les outils de visualisation, illustrés avec R (avec ses nombreux packages, ggplot, plotly, dygraphs, treemaps, leaflet etc).
- Développer le sens de la créativité 
- Créer un compte github et publier les projets réalisés


## Pré-requis

Il est préférabe d'avoir les quelques pré-requis suivants, néanmions des rappels seront faits au début de chaque session.

- Connaissances de R et RStudio
- Connaissance du langage markdown
- Connaissances de base html
- Bases de données structurées (table, json, xml, etc.)
- Notions de base sur le text-mining


## Outils

Outil de programmation principal : rmarkdown

Packages R : 

- Grahiques : plotly, ggplot2
- Cartographie : Leaflet
- Séries temporelles : Dygraphs
- Application web : Shiny
- Webscrapping : XML et rselenium

De nombreux packages sont à découvrir par vous-mêmes.


## Projets

suggestion de projets :

- Étude de l'implantation d'un réseau d'agents généraux 
- Visualisation de la base accidents en utilisant [flexdashboard](http://rmarkdown.rstudio.com/flexdashboard/)
- Text mining des avis clients, visualisation des sentiments
- Visualisation d'un algorithme de machine learning
- Assurance météo et étude de la météo d'une ville donnée 
- Création de zoniers météo (étude de la dépendance géographique)

Vous pouvez également créer des visualisations avec les bases de données ou les modèles que vous traiter dans d'autres matières. Deux approches peuvent être utilisées pour trouver des idées: 

- examiner les bases de données, et lorsque vous voulez expliquer certaines relations entre variables, vous penserez à les illustrer avec des graphiques pour les représenter de façon esthétique, interactive, dynamique, etc. (par exemple, lorsque vous réalisez un QQplot, il est intéressant de pouvoir lire les valeurs en cliquant sur les points)
- parcourir des exemples de graphiques, pour comprendre les particularités de certains graphiques (voir les exemples de la bibliothèque D3js.)

Proposez des projets, soyez créatif et entrepreneur.


## Conseils

Pour chaque séance, il est conseillé de suivre ces quelques consignes générales : 

- Lire la présentation et les questions de la séance en entier, et garder en tête les objectifs.
- Commencer à créer un fichier rmd et rappeler les objectifs avec vos propres mots. Ce fichier sera le fichier de travail principal où vous introduirez les questions, les réponses en code, et les interprétations des résultats.
- Il est tout à fait possible de rajouter des commentaires supplémentaires pour illustrer les objectifs.
- Le rapport rédigé avec le fichier rmd peut suivre un plan personnalisé.
- Le rapport final pourra être généré en html et un délégué pourra les regrouper et les publier sur ce site sous l'onglet "projets d'étudiants".


# 1. Bases datavis

Manipulation des outils de base avec R

- Rappels de la programmation sous R
- Interface du logiciel RStudio
- Création et manipulation des fichiers rmarkdown

Quelques notions de base pour la visualisation : 

- Graphiques 2D et 3D
- Cartographie
- Treemap
- Visualisation des series temporelles

Pour enrichir la base de données, il est parfois utile de récupérer des données publiques sur internet.

- structure des pages web
- techniques de base du web scraping


# 2. Modèles statistiques

Les notions classiques statistiques et actuarielles sont illustrées avec des packages R interactif et dynamique :

- Copules, distribution, fonction de répartition, QQplot, Hill plot
- Simulation des nombres selon une loi donnée 
- Modèles de taux
- Analyse de la sinistralité
- Chain Ladder et l'intervalle de confiance des ultimes


# 3. Etude géograhique

L'étude des données géographiques est importante en assurance.

- Données météorologiques
- Données géographiques sur les risques de catastrophes naturelles
- Carte avec les variables météorologiques

Visualisation des accidents selon la situation géographique


# 4. Visualisation des algorithmes

Avec la visualisation, l'explication de certains algorithmes devient plus intuitive. C'est l'occasion d'apprendre certains algorithmes en visulisation le principe et les résultats de prédiction.


Exemples : 

https://blog.bigml.com/2013/04/19/a-new-way-to-visualize-decision-trees/
http://www.r2d3.us/visual-intro-to-machine-learning-part-1/


# 5. Application web

Shiny offre la possibilité de construire une application web avec R.
