---
title: "Séance 1. Comparaison"
output:
    html_document:
      toc: true
      toc_float: true
      number_sections: false
      theme: journal
      highlight: textmate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```

```{r eval=FALSE, echo=FALSE}
rmarkdown::render_site()
install.packages("knitr")
install.packages("rmarkdown")
install.packages("tabplot")
```

```{r}
library(ggplot2)
library(data.table)
```

# Données

Dans la série de données iris, on peut comparer les différentes valeurs des 4 variables des fleurs.
L'objectif est de montrer les valeurs d'une ou de plusieurs variables en fonction des trois espèces.


# Bar plot

```{r}
data=data.table(iris)
res=data[,.(m=mean(Sepal.Length)),by=Species]
barplot(res$m,names.arg=res$Species,
        main="Longueurs moyennes des sépales en fonction des espèces")
```

# Boxplot
```{r}
p <- ggplot(iris, aes(Species, Sepal.Length))+ geom_boxplot()
p

```

# Violin plot

```{r}
p <- ggplot(iris, aes(Species, Sepal.Length))
p + geom_violin()

```

# Tabplot

```{r}
library(tabplot)
tableplot(iris, sortCol="Species")
```


# Parallele Cordinates

```{r}
library(MASS)
parcoord(iris[1:4], col=iris$Species)
```

